config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "users#index"

  resources :users, only: [:index, :create]
  resources :sessions, only: [:create]
  resources :dashboards

  get "log_out" => "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :name, :email, presence: true
  validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { :case_sensitive => false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def current_user
		User.find(session[:user_id]) if session[:user_id]
	end

	def require_login
		unless session[:user_id]
		flash[:errors] = ["You must login first"]
		redirect_to root_path
		end
	end


end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	before_action :require_login

	def index
		user_id = session[:user_id]
		@name = User.find(user_id)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to :dashboards
		else
			flash[:errors] = ["Invalid Combination"]
			redirect_to :users
		end
	end


	def destroy
		reset_session
		redirect_to :root
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@user = User.new
	end

	def create
		user = User.new(user_params)
		if user.save
			session[:user_id] = user.id
			redirect_to :users
		else
			flash[:errors] = user.errors.full_messages
			redirect_to :users	
		end
	end

	private 
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/index.html.erb
<h1>Admin Dashboard</h1>


<h2>Welcome <%= @name.name %></h2>

<%= link_to "Log out", "/log_out" %>

app/views/layouts/sapplication.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<style type="text/css">
	div {
  margin:0 auto;
  width:398px
}
input {
  margin-bottom:3px;
  padding:10px;
  width: 100%;
  border:1px solid #CCC
}
button {
  padding:10px
}
label {
  cursor:pointer
}
#form-switch {
  display:none
}
#register-form {
  display:none
}
#form-switch:checked~#register-form {
  display:block
}
#form-switch:checked~#login-form {
  display:none
}
</style>




<h1 style="text-align: center;">Login & Register</h1>





<input type='checkbox' id='form-switch'>


<div id='login-form' >
  <%= form_tag sessions_path do  %>

  		<%= label_tag :email%>:
		<%= email_field_tag :email %>

		<%= label_tag :password%>:
		<%= password_field_tag :password %>

		<%= submit_tag "Sign In" %>

  <% end  %>
  <label for='form-switch'><span>Register</span></label>
</div>













<% if flash[:errors] %>
<div id="row">
	<% flash[:errors].each do |e| %>
		<%= e %>	
		<br>
	<% end %>	
</div>
<% end %>

<div id='register-form'>


	<%= form_for @user do |f|  %>
		<%= f.label :name%>:
		<%= f.text_field :name %>

		<%= f.label :email%>:
		<%= f.email_field :email %>

		<%= f.label :password%>:
		<%= f.password_field :password %>

		<%= f.label :password_confirmation%>:
		<%= f.text_field :password_confirmation %>

	<%= f.submit %>

  <label for='form-switch'>Already Member ? Sign In Now..</label>
  <% end %>
</div>